#!/bin/bash

clang-15 -Wall -Wextra iter_quine.c -o iter_quine &&
./iter_quine > gen_iter_quine.c &&
cat gen_iter_quine.c &&
echo &&
echo &&
echo &&
echo

while [ "$?" == 0 ]
do
	clang-15 -Wall -Wextra gen_iter_quine.c -o gen_iter_quine &&
	./gen_iter_quine > gen_iter_quine.c &&
	cat gen_iter_quine.c &&
	echo &&
	echo &&
	echo &&
	echo
done
