#!/bin/bash

clang-15 -Wall -Wextra quine.c -o quine &&
echo "compiled original quine source" &&
{
	./quine > gen_quine.c || {
		echo "quine_loop: ERROR: original quine execution failed" 1>&2
		exit 1
	}
} &&
echo "generated next source iteration with compiled original quine"

while [ "$?" == 0 ]
do
	clang-15 -Wall -Wextra gen_quine.c -o gen_quine &&
	echo "compiled quine" &&
	./gen_quine > gen_quine.c &&
	echo "generated next source iteration with compiled quine"
done

echo "quine_loop: ERROR: something went wrong in the loop" 1>&2 &&
exit 1
